use relay_shared::protocol::{ListenerConfig, LoadBalanceStrategy, Protocol};
use std::collections::BTreeMap;
use std::fs::{self, File};
use std::io::Write;
use std::path::PathBuf;
use std::process::Command;

#[derive(Clone, Debug)]
pub struct NginxSniConfig {
    pub enabled: bool,
    pub conf_path: PathBuf,
    pub test_cmd: String,
    pub reload_cmd: String,
    pub default_backend: String,
    pub access_log_path: String,
}

impl Default for NginxSniConfig {
    fn default() -> Self {
        Self {
            enabled: false,
            conf_path: PathBuf::from("/etc/nginx/stream.d/relay-panel-sni.conf"),
            test_cmd: "nginx -t".to_string(),
            reload_cmd: "systemctl reload nginx".to_string(),
            default_backend: "127.0.0.1:9".to_string(),
            access_log_path: "/var/log/nginx/sni-router.log".to_string(),
        }
    }
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct NginxSniRule {
    pub rule_id: i64,
    pub listen_port: u16,
    pub sni: String,
    pub targets: Vec<String>,
    pub load_balance_strategy: LoadBalanceStrategy,
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct NginxSniPlan {
    rules: Vec<NginxSniRule>,
    default_backend: String,
    access_log_path: String,
}

impl NginxSniPlan {
    pub fn from_listeners(
        listeners: &[ListenerConfig],
        default_backend: &str,
        access_log_path: &str,
    ) -> Result<Self, String> {
        let mut rules = Vec::new();
        for l in listeners {
            if l.protocol != Protocol::Tcp {
                tracing::warn!(
                    "rule {}: nginx_sni only supports TCP; skipping {:?} listener on port {}",
                    l.rule_id,
                    l.protocol,
                    l.port
                );
                continue;
            }
            let Some(sni) = l.sni.as_deref().map(str::trim).filter(|s| !s.is_empty()) else {
                tracing::warn!(
                    "rule {}: nginx_sni listener on port {} has no SNI; skipping",
                    l.rule_id,
                    l.port
                );
                continue;
            };
            let targets: Vec<String> = l
                .targets
                .iter()
                .map(|t| t.trim())
                .filter(|t| !t.is_empty())
                .map(ToOwned::to_owned)
                .collect();
            if targets.is_empty() {
                tracing::warn!(
                    "rule {}: nginx_sni listener on port {} has no backend target; skipping",
                    l.rule_id,
                    l.port
                );
                continue;
            }
            rules.push(NginxSniRule {
                rule_id: l.rule_id,
                listen_port: l.port,
                sni: sni.to_ascii_lowercase(),
                targets,
                load_balance_strategy: l.load_balance_strategy,
            });
        }
        rules.sort_by(|a, b| {
            (a.listen_port, a.sni.as_str(), a.rule_id).cmp(&(
                b.listen_port,
                b.sni.as_str(),
                b.rule_id,
            ))
        });
        if rules
            .windows(2)
            .any(|pair| pair[0].listen_port == pair[1].listen_port && pair[0].sni == pair[1].sni)
        {
            return Err("duplicate Nginx SNI listener route".to_string());
        }
        Ok(Self {
            rules,
            default_backend: default_backend.to_string(),
            access_log_path: access_log_path.to_string(),
        })
    }

    pub fn rule_id_for(&self, port: u16, sni: &str) -> Option<i64> {
        let sni = sni.trim().to_ascii_lowercase();
        self.rules
            .iter()
            .find(|r| r.listen_port == port && r.sni == sni)
            .map(|r| r.rule_id)
    }

    pub fn render(&self) -> String {
        let mut by_port: BTreeMap<u16, Vec<&NginxSniRule>> = BTreeMap::new();
        for rule in &self.rules {
            by_port.entry(rule.listen_port).or_default().push(rule);
        }

        let mut out = String::new();
        out.push_str("# generated by relay-node; do not edit\n");
        out.push_str("# managed mode: nginx_sni\n\n");
        out.push_str("log_format relay_panel_sni_traffic '$msec|$server_port|$ssl_preread_server_name|$relay_panel_sni_rule_id|$bytes_sent|$bytes_received|$session_time';\n");
        out.push_str(&format!(
            "access_log {} relay_panel_sni_traffic;\n\n",
            quote_nginx_string(&self.access_log_path)
        ));

        let default_upstream = "relay_panel_sni_default_backend";
        out.push_str(&format!("upstream {} {{\n", default_upstream));
        out.push_str(&format!(
            "    server {} max_fails=1 fail_timeout=10s;\n",
            escape_nginx_upstream_server(&self.default_backend)
        ));
        out.push_str("}\n\n");

        for rule in &self.rules {
            out.push_str(&format!("upstream {} {{\n", upstream_name(rule)));
            for (idx, target) in effective_targets(rule).iter().enumerate() {
                let backup = rule.load_balance_strategy == LoadBalanceStrategy::Failover && idx > 0;
                out.push_str(&format!(
                    "    server {} max_fails=1 fail_timeout=10s{};\n",
                    escape_nginx_upstream_server(target),
                    if backup { " backup" } else { "" }
                ));
            }
            out.push_str("}\n\n");
        }

        out.push_str("map \"$server_port:$ssl_preread_server_name\" $relay_panel_sni_backend {\n");
        for rule in &self.rules {
            out.push_str(&format!(
                "    {} {};\n",
                map_key_for(rule),
                upstream_name(rule)
            ));
        }
        out.push_str(&format!("    default {};\n", default_upstream));
        out.push_str("}\n\n");

        out.push_str("map \"$server_port:$ssl_preread_server_name\" $relay_panel_sni_rule_id {\n");
        for rule in &self.rules {
            out.push_str(&format!("    {} {};\n", map_key_for(rule), rule.rule_id));
        }
        out.push_str("    default 0;\n");
        out.push_str("}\n\n");

        for (port, _rules) in by_port {
            out.push_str("server {\n");
            out.push_str(&format!("    listen {};\n", port));
            out.push_str("    proxy_pass $relay_panel_sni_backend;\n");
            out.push_str("    ssl_preread on;\n");
            out.push_str("}\n\n");
        }
        out
    }
}

fn effective_targets(rule: &NginxSniRule) -> Vec<&String> {
    match rule.load_balance_strategy {
        LoadBalanceStrategy::First => rule.targets.iter().take(1).collect(),
        LoadBalanceStrategy::RoundRobin | LoadBalanceStrategy::Failover => {
            rule.targets.iter().collect()
        }
    }
}

fn upstream_name(rule: &NginxSniRule) -> String {
    format!(
        "relay_panel_sni_rule_{}_{}_{}",
        rule.rule_id,
        rule.listen_port,
        sanitize_nginx_name(&rule.sni)
    )
}

fn map_key_for(rule: &NginxSniRule) -> String {
    format!("~*^{}:{}$", rule.listen_port, escape_nginx_regex(&rule.sni))
}

fn sanitize_nginx_name(s: &str) -> String {
    let mut out = String::new();
    for c in s.chars() {
        if c.is_ascii_alphanumeric() {
            out.push(c.to_ascii_lowercase());
        } else {
            out.push('_');
        }
    }
    let trimmed = out.trim_matches('_');
    if trimmed.is_empty() {
        "unknown".to_string()
    } else {
        trimmed.to_string()
    }
}

fn escape_nginx_regex(s: &str) -> String {
    let mut out = String::new();
    for c in s.chars() {
        if matches!(
            c,
            '\\' | '.' | '+' | '*' | '?' | '^' | '$' | '(' | ')' | '[' | ']' | '{' | '}' | '|'
        ) {
            out.push('\\');
        }
        out.push(c);
    }
    out
}

#[derive(Debug)]
pub enum ApplyError {
    Io(std::io::Error),
    CommandFailed { cmd: String, detail: String },
}

impl std::fmt::Display for ApplyError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            ApplyError::Io(e) => write!(f, "{}", e),
            ApplyError::CommandFailed { cmd, detail } => write!(f, "{} failed: {}", cmd, detail),
        }
    }
}

impl std::error::Error for ApplyError {}

impl From<std::io::Error> for ApplyError {
    fn from(e: std::io::Error) -> Self {
        ApplyError::Io(e)
    }
}

pub fn apply_plan(plan: &NginxSniPlan, cfg: &NginxSniConfig) -> Result<(), ApplyError> {
    apply_rendered(plan.render().as_bytes(), cfg)
}

/// Apply a second Node-owned Nginx fragment with the same test/reload rollback
/// contract as the stream router. Used by the local Reality TLS wrappers.
pub fn apply_rendered(contents: &[u8], cfg: &NginxSniConfig) -> Result<(), ApplyError> {
    if !cfg.enabled {
        return Ok(());
    }

    if let Some(parent) = cfg.conf_path.parent() {
        fs::create_dir_all(parent)?;
    }

    let previous = match fs::read(&cfg.conf_path) {
        Ok(contents) => Some(contents),
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => None,
        Err(e) => return Err(e.into()),
    };
    replace_durably(&cfg.conf_path, contents)?;

    if let Err(e) = run_shell(&cfg.test_cmd) {
        restore_previous(&cfg.conf_path, previous.as_deref())?;
        return Err(e);
    }
    if let Err(e) = run_shell(&cfg.reload_cmd) {
        restore_previous(&cfg.conf_path, previous.as_deref())?;
        // The previous config is only a real rollback once Nginx has accepted
        // and reloaded it again. Preserve the original apply failure either way.
        if let Err(restore_err) = run_shell(&cfg.test_cmd).and_then(|_| run_shell(&cfg.reload_cmd))
        {
            tracing::error!(
                "nginx_sni rollback runtime restore failed after reload failure: {}",
                restore_err
            );
        }
        return Err(e);
    }
    tracing::info!(
        "applied nginx_sni config: {} rule(s), path={}",
        "managed",
        cfg.conf_path.display()
    );
    Ok(())
}

/// Restore a managed fragment after a later cross-component transaction step
/// fails. This intentionally tests and reloads the old runtime too.
pub fn restore_rendered(previous: Option<&[u8]>, cfg: &NginxSniConfig) -> Result<(), ApplyError> {
    if !cfg.enabled {
        return Ok(());
    }
    restore_previous(&cfg.conf_path, previous)?;
    run_shell(&cfg.test_cmd)?;
    run_shell(&cfg.reload_cmd)
}

fn temp_path(path: &std::path::Path) -> PathBuf {
    let mut temp = path.as_os_str().to_os_string();
    temp.push(".tmp");
    PathBuf::from(temp)
}

/// Persist `contents` before atomically replacing `path`. The temp file lives
/// beside the target so rename is atomic on the configured filesystem.
fn replace_durably(path: &std::path::Path, contents: &[u8]) -> Result<(), ApplyError> {
    let temp = temp_path(path);
    let write_result = (|| -> Result<(), std::io::Error> {
        let mut file = File::create(&temp)?;
        file.write_all(contents)?;
        file.flush()?;
        file.sync_all()?;
        fs::rename(&temp, path)?;
        sync_parent(path)?;
        Ok(())
    })();
    if write_result.is_err() {
        let _ = fs::remove_file(&temp);
    }
    write_result.map_err(ApplyError::Io)
}

fn restore_previous(path: &std::path::Path, previous: Option<&[u8]>) -> Result<(), ApplyError> {
    match previous {
        Some(contents) => replace_durably(path, contents),
        None => {
            match fs::remove_file(path) {
                Ok(()) => sync_parent(path)?,
                Err(e) if e.kind() == std::io::ErrorKind::NotFound => {}
                Err(e) => return Err(e.into()),
            }
            Ok(())
        }
    }
}

fn sync_parent(path: &std::path::Path) -> Result<(), std::io::Error> {
    if let Some(parent) = path.parent() {
        File::open(parent)?.sync_all()?;
    }
    Ok(())
}

fn run_shell(cmd: &str) -> Result<(), ApplyError> {
    let output = Command::new("sh").arg("-c").arg(cmd).output()?;
    if output.status.success() {
        return Ok(());
    }
    let stdout = String::from_utf8_lossy(&output.stdout);
    let stderr = String::from_utf8_lossy(&output.stderr);
    let detail = format!(
        "status={} stdout={} stderr={}",
        output.status, stdout, stderr
    );
    Err(ApplyError::CommandFailed {
        cmd: cmd.to_string(),
        detail,
    })
}

fn quote_nginx_string(s: &str) -> String {
    format!("\"{}\"", s.replace('\\', "\\\\").replace('"', "\\\""))
}

fn escape_nginx_upstream_server(s: &str) -> String {
    if s.chars()
        .all(|c| c.is_ascii_alphanumeric() || matches!(c, '.' | '-' | '_' | ':' | '[' | ']'))
    {
        s.to_string()
    } else {
        quote_nginx_string(s)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use relay_shared::protocol::{LoadBalanceStrategy, NodeTransport};

    fn listener(
        rule_id: i64,
        port: u16,
        sni: &str,
        targets: &[&str],
        load_balance_strategy: LoadBalanceStrategy,
    ) -> ListenerConfig {
        ListenerConfig {
            camouflage_required: false,
            rule_id,
            port,
            protocol: Protocol::Tcp,
            node_transport: NodeTransport::NginxSni,
            ws_path: None,
            sni: Some(sni.to_string()),
            targets: targets.iter().map(|t| t.to_string()).collect(),
            load_balance_strategy,
            upload_limit_bps: None,
            download_limit_bps: None,
            max_connections: None,
        }
    }

    #[test]
    fn renders_one_server_per_shared_port() {
        let plan = NginxSniPlan::from_listeners(
            &[
                listener(
                    1,
                    443,
                    "op1.example.com",
                    &["10.0.0.1:55443"],
                    LoadBalanceStrategy::First,
                ),
                listener(
                    2,
                    443,
                    "op2.example.com",
                    &["10.0.0.2:55443"],
                    LoadBalanceStrategy::First,
                ),
                listener(
                    3,
                    8443,
                    "op3.example.com",
                    &["10.0.0.3:55443"],
                    LoadBalanceStrategy::First,
                ),
            ],
            "127.0.0.1:9",
            "/var/log/nginx/sni-router.log",
        )
        .unwrap();
        let rendered = plan.render();
        assert!(rendered
            .contains("map \"$server_port:$ssl_preread_server_name\" $relay_panel_sni_backend"));
        assert!(rendered
            .contains("~*^443:op1\\.example\\.com$ relay_panel_sni_rule_1_443_op1_example_com;"));
        assert!(rendered
            .contains("~*^443:op2\\.example\\.com$ relay_panel_sni_rule_2_443_op2_example_com;"));
        assert!(rendered.contains("server 10.0.0.1:55443 max_fails=1 fail_timeout=10s;"));
        assert!(rendered.contains("listen 443;"));
        assert!(rendered.contains("listen 8443;"));
        assert!(rendered
            .contains("access_log \"/var/log/nginx/sni-router.log\" relay_panel_sni_traffic;"));
    }

    #[test]
    fn renders_upstreams_for_multi_target_strategies() {
        let plan = NginxSniPlan::from_listeners(
            &[
                listener(
                    1,
                    443,
                    "op1.example.com",
                    &["10.0.0.1:55443", "10.0.0.2:55443"],
                    LoadBalanceStrategy::RoundRobin,
                ),
                listener(
                    2,
                    443,
                    "op2.example.com",
                    &["10.0.0.3:55443", "10.0.0.4:55443"],
                    LoadBalanceStrategy::Failover,
                ),
                listener(
                    3,
                    443,
                    "op3.example.com",
                    &["10.0.0.5:55443", "10.0.0.6:55443"],
                    LoadBalanceStrategy::First,
                ),
            ],
            "127.0.0.1:8443",
            "/var/log/nginx/sni-router.log",
        )
        .unwrap();
        let rendered = plan.render();
        assert!(rendered.contains("upstream relay_panel_sni_rule_1_443_op1_example_com"));
        assert!(rendered.contains("server 10.0.0.1:55443 max_fails=1 fail_timeout=10s;"));
        assert!(rendered.contains("server 10.0.0.2:55443 max_fails=1 fail_timeout=10s;"));
        assert!(rendered.contains("server 10.0.0.4:55443 max_fails=1 fail_timeout=10s backup;"));
        assert!(rendered.contains("server 10.0.0.5:55443 max_fails=1 fail_timeout=10s;"));
        assert!(!rendered.contains("server 10.0.0.6:55443 max_fails=1 fail_timeout=10s;"));
    }

    #[test]
    fn looks_up_rule_id_by_port_and_sni() {
        let plan = NginxSniPlan::from_listeners(
            &[listener(
                7,
                443,
                "OP1.Example.COM",
                &["10.0.0.1:55443"],
                LoadBalanceStrategy::First,
            )],
            "127.0.0.1:8443",
            "/var/log/nginx/sni-router.log",
        )
        .unwrap();
        assert_eq!(plan.rule_id_for(443, "op1.example.com"), Some(7));
        assert_eq!(plan.rule_id_for(8443, "op1.example.com"), None);
    }

    #[test]
    fn listener_route_is_the_only_remote_route_authority() {
        let plan = NginxSniPlan::from_listeners(
            &[listener(
                7,
                443,
                "reality.example.com",
                &["141.11.219.133:55443"],
                LoadBalanceStrategy::First,
            )],
            "127.0.0.1:9",
            "/tmp/relay-panel-test.log",
        )
        .unwrap();
        let rendered = plan.render();
        assert_eq!(rendered.matches("listen 443;").count(), 1);
        assert!(rendered.contains("141.11.219.133:55443"));
        assert!(!rendered.contains("127.0.0.1:24443"));
    }

    #[test]
    fn duplicate_public_port_and_sni_is_rejected() {
        let result = NginxSniPlan::from_listeners(
            &[
                listener(
                    7,
                    443,
                    "same.example.com",
                    &["141.11.219.133:55443"],
                    LoadBalanceStrategy::First,
                ),
                listener(
                    8,
                    443,
                    "SAME.EXAMPLE.COM",
                    &["192.0.2.2:55443"],
                    LoadBalanceStrategy::First,
                ),
            ],
            "127.0.0.1:9",
            "/tmp/relay-panel-test.log",
        );
        assert!(result.is_err());
    }

    fn unique_path(label: &str) -> PathBuf {
        let stamp = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap()
            .as_nanos();
        std::env::temp_dir().join(format!(
            "relay-panel-nginx-{label}-{}-{stamp}",
            std::process::id()
        ))
    }

    fn plan_for(sni: &str) -> NginxSniPlan {
        NginxSniPlan::from_listeners(
            &[listener(
                1,
                443,
                sni,
                &["127.0.0.1:55443"],
                LoadBalanceStrategy::First,
            )],
            "127.0.0.1:9",
            "/tmp/relay-panel-test.log",
        )
        .unwrap()
    }

    fn test_config(path: PathBuf, test_cmd: &str, reload_cmd: &str) -> NginxSniConfig {
        NginxSniConfig {
            enabled: true,
            conf_path: path,
            test_cmd: test_cmd.to_string(),
            reload_cmd: reload_cmd.to_string(),
            default_backend: "127.0.0.1:9".to_string(),
            access_log_path: "/tmp/relay-panel-test.log".to_string(),
        }
    }

    fn cleanup(path: &PathBuf) {
        let _ = std::fs::remove_file(path);
        let _ = std::fs::remove_file(temp_path(path));
        let _ = std::fs::remove_dir_all(path.parent().unwrap());
    }

    #[test]
    fn nginx_test_failure_restores_old_config() {
        let path = unique_path("test-failure").join("relay.conf");
        std::fs::create_dir_all(path.parent().unwrap()).unwrap();
        std::fs::write(&path, "old-config").unwrap();
        let cfg = test_config(path.clone(), "false", "true");

        assert!(apply_plan(&plan_for("new.example.com"), &cfg).is_err());
        assert_eq!(std::fs::read_to_string(&path).unwrap(), "old-config");
        cleanup(&path);
    }

    #[test]
    fn nginx_test_failure_without_old_config_removes_new_file() {
        let path = unique_path("test-no-old").join("relay.conf");
        let cfg = test_config(path.clone(), "false", "true");

        assert!(apply_plan(&plan_for("new.example.com"), &cfg).is_err());
        assert!(
            !path.exists(),
            "failed first apply must restore file absence"
        );
        cleanup(&path);
    }

    #[test]
    fn reload_failure_restores_disk_and_attempts_old_runtime_restore() {
        let path = unique_path("reload-failure").join("relay.conf");
        let marker = path.with_extension("runtime-restored");
        std::fs::create_dir_all(path.parent().unwrap()).unwrap();
        std::fs::write(&path, "old-config").unwrap();
        let reload_cmd = format!(
            "if grep -q new.example.com {}; then exit 1; else printf restored > {}; fi",
            path.display(),
            marker.display()
        );
        let cfg = test_config(path.clone(), "true", &reload_cmd);

        assert!(apply_plan(&plan_for("new.example.com"), &cfg).is_err());
        assert_eq!(std::fs::read_to_string(&path).unwrap(), "old-config");
        assert_eq!(std::fs::read_to_string(&marker).unwrap(), "restored");
        let _ = std::fs::remove_file(marker);
        cleanup(&path);
    }

    #[test]
    fn matching_disk_content_does_not_skip_retry() {
        let path = unique_path("same-content").join("relay.conf");
        let marker = path.with_extension("reload-count");
        let plan = plan_for("same.example.com");
        std::fs::create_dir_all(path.parent().unwrap()).unwrap();
        std::fs::write(&path, plan.render()).unwrap();
        let reload_cmd = format!("printf x >> {}; false", marker.display());
        let cfg = test_config(path.clone(), "true", &reload_cmd);

        assert!(apply_plan(&plan, &cfg).is_err());
        assert_eq!(
            std::fs::read_to_string(&marker).unwrap(),
            "xx",
            "apply and old-runtime restore must both run reload despite matching disk content"
        );
        let _ = std::fs::remove_file(marker);
        cleanup(&path);
    }
}
