use relay_shared::protocol::{ListenerConfig, LoadBalanceStrategy, Protocol};
use std::collections::BTreeMap;
use std::path::PathBuf;
use std::process::Command;

#[derive(Clone, Debug)]
pub struct NginxSniConfig {
    pub enabled: bool,
    pub conf_path: PathBuf,
    pub test_cmd: String,
    pub reload_cmd: String,
    pub default_backend: String,
    pub access_log_path: String,
}

impl Default for NginxSniConfig {
    fn default() -> Self {
        Self {
            enabled: false,
            conf_path: PathBuf::from("/etc/nginx/stream.d/relay-panel-sni.conf"),
            test_cmd: "nginx -t".to_string(),
            reload_cmd: "systemctl reload nginx".to_string(),
            default_backend: "127.0.0.1:9".to_string(),
            access_log_path: "/var/log/nginx/sni-router.log".to_string(),
        }
    }
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct NginxSniRule {
    pub rule_id: i64,
    pub listen_port: u16,
    pub sni: String,
    pub targets: Vec<String>,
    pub load_balance_strategy: LoadBalanceStrategy,
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct NginxSniPlan {
    rules: Vec<NginxSniRule>,
    default_backend: String,
    access_log_path: String,
}

impl NginxSniPlan {
    pub fn from_listeners(
        listeners: &[ListenerConfig],
        default_backend: &str,
        access_log_path: &str,
    ) -> Self {
        let mut rules = Vec::new();
        for l in listeners {
            if l.protocol != Protocol::Tcp {
                tracing::warn!(
                    "rule {}: nginx_sni only supports TCP; skipping {:?} listener on port {}",
                    l.rule_id,
                    l.protocol,
                    l.port
                );
                continue;
            }
            let Some(sni) = l.sni.as_deref().map(str::trim).filter(|s| !s.is_empty()) else {
                tracing::warn!(
                    "rule {}: nginx_sni listener on port {} has no SNI; skipping",
                    l.rule_id,
                    l.port
                );
                continue;
            };
            let targets: Vec<String> = l
                .targets
                .iter()
                .map(|t| t.trim())
                .filter(|t| !t.is_empty())
                .map(ToOwned::to_owned)
                .collect();
            if targets.is_empty() {
                tracing::warn!(
                    "rule {}: nginx_sni listener on port {} has no backend target; skipping",
                    l.rule_id,
                    l.port
                );
                continue;
            }
            rules.push(NginxSniRule {
                rule_id: l.rule_id,
                listen_port: l.port,
                sni: sni.to_ascii_lowercase(),
                targets,
                load_balance_strategy: l.load_balance_strategy,
            });
        }
        rules.sort_by(|a, b| {
            (a.listen_port, a.sni.as_str(), a.rule_id).cmp(&(
                b.listen_port,
                b.sni.as_str(),
                b.rule_id,
            ))
        });
        rules.dedup_by(|a, b| a.listen_port == b.listen_port && a.sni == b.sni);
        Self {
            rules,
            default_backend: default_backend.to_string(),
            access_log_path: access_log_path.to_string(),
        }
    }

    pub fn rule_id_for(&self, port: u16, sni: &str) -> Option<i64> {
        let sni = sni.trim().to_ascii_lowercase();
        self.rules
            .iter()
            .find(|r| r.listen_port == port && r.sni == sni)
            .map(|r| r.rule_id)
    }

    pub fn render(&self) -> String {
        let mut by_port: BTreeMap<u16, Vec<&NginxSniRule>> = BTreeMap::new();
        for rule in &self.rules {
            by_port.entry(rule.listen_port).or_default().push(rule);
        }

        let mut out = String::new();
        out.push_str("# generated by relay-node; do not edit\n");
        out.push_str("# managed mode: nginx_sni\n\n");
        out.push_str("log_format relay_panel_sni_traffic '$msec|$server_port|$ssl_preread_server_name|$relay_panel_sni_rule_id|$bytes_sent|$bytes_received|$session_time';\n");
        out.push_str(&format!(
            "access_log {} relay_panel_sni_traffic;\n\n",
            quote_nginx_string(&self.access_log_path)
        ));

        let default_upstream = "relay_panel_sni_default_backend";
        out.push_str(&format!("upstream {} {{\n", default_upstream));
        out.push_str(&format!(
            "    server {} max_fails=1 fail_timeout=10s;\n",
            escape_nginx_upstream_server(&self.default_backend)
        ));
        out.push_str("}\n\n");

        for rule in &self.rules {
            out.push_str(&format!("upstream {} {{\n", upstream_name(rule)));
            for (idx, target) in effective_targets(rule).iter().enumerate() {
                let backup = rule.load_balance_strategy == LoadBalanceStrategy::Failover && idx > 0;
                out.push_str(&format!(
                    "    server {} max_fails=1 fail_timeout=10s{};\n",
                    escape_nginx_upstream_server(target),
                    if backup { " backup" } else { "" }
                ));
            }
            out.push_str("}\n\n");
        }

        out.push_str("map \"$server_port:$ssl_preread_server_name\" $relay_panel_sni_backend {\n");
        for rule in &self.rules {
            out.push_str(&format!(
                "    {} {};\n",
                map_key_for(rule),
                upstream_name(rule)
            ));
        }
        out.push_str(&format!("    default {};\n", default_upstream));
        out.push_str("}\n\n");

        out.push_str("map \"$server_port:$ssl_preread_server_name\" $relay_panel_sni_rule_id {\n");
        for rule in &self.rules {
            out.push_str(&format!("    {} {};\n", map_key_for(rule), rule.rule_id));
        }
        out.push_str("    default 0;\n");
        out.push_str("}\n\n");

        for (port, _rules) in by_port {
            out.push_str("server {\n");
            out.push_str(&format!("    listen {};\n", port));
            out.push_str("    proxy_pass $relay_panel_sni_backend;\n");
            out.push_str("    ssl_preread on;\n");
            out.push_str("}\n\n");
        }
        out
    }
}

fn effective_targets(rule: &NginxSniRule) -> Vec<&String> {
    match rule.load_balance_strategy {
        LoadBalanceStrategy::First => rule.targets.iter().take(1).collect(),
        LoadBalanceStrategy::RoundRobin | LoadBalanceStrategy::Failover => {
            rule.targets.iter().collect()
        }
    }
}

fn upstream_name(rule: &NginxSniRule) -> String {
    format!(
        "relay_panel_sni_rule_{}_{}_{}",
        rule.rule_id,
        rule.listen_port,
        sanitize_nginx_name(&rule.sni)
    )
}

fn map_key_for(rule: &NginxSniRule) -> String {
    format!("~*^{}:{}$", rule.listen_port, escape_nginx_regex(&rule.sni))
}

fn sanitize_nginx_name(s: &str) -> String {
    let mut out = String::new();
    for c in s.chars() {
        if c.is_ascii_alphanumeric() {
            out.push(c.to_ascii_lowercase());
        } else {
            out.push('_');
        }
    }
    let trimmed = out.trim_matches('_');
    if trimmed.is_empty() {
        "unknown".to_string()
    } else {
        trimmed.to_string()
    }
}

fn escape_nginx_regex(s: &str) -> String {
    let mut out = String::new();
    for c in s.chars() {
        if matches!(
            c,
            '\\' | '.' | '+' | '*' | '?' | '^' | '$' | '(' | ')' | '[' | ']' | '{' | '}' | '|'
        ) {
            out.push('\\');
        }
        out.push(c);
    }
    out
}

#[derive(Debug)]
pub enum ApplyError {
    Io(std::io::Error),
    CommandFailed { cmd: String, detail: String },
}

impl std::fmt::Display for ApplyError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            ApplyError::Io(e) => write!(f, "{}", e),
            ApplyError::CommandFailed { cmd, detail } => write!(f, "{} failed: {}", cmd, detail),
        }
    }
}

impl std::error::Error for ApplyError {}

impl From<std::io::Error> for ApplyError {
    fn from(e: std::io::Error) -> Self {
        ApplyError::Io(e)
    }
}

pub fn apply_plan(plan: &NginxSniPlan, cfg: &NginxSniConfig) -> Result<(), ApplyError> {
    if !cfg.enabled {
        return Ok(());
    }

    let rendered = plan.render();
    let current = std::fs::read_to_string(&cfg.conf_path).ok();
    if current.as_deref() == Some(rendered.as_str()) {
        tracing::debug!("nginx_sni config unchanged at {}", cfg.conf_path.display());
        return Ok(());
    }

    if let Some(parent) = cfg.conf_path.parent() {
        std::fs::create_dir_all(parent)?;
    }

    let previous = current;
    std::fs::write(&cfg.conf_path, rendered)?;

    if let Err(e) = run_shell(&cfg.test_cmd) {
        if let Some(old) = previous {
            let _ = std::fs::write(&cfg.conf_path, old);
        } else {
            let _ = std::fs::remove_file(&cfg.conf_path);
        }
        return Err(e);
    }
    run_shell(&cfg.reload_cmd)?;
    tracing::info!(
        "applied nginx_sni config: {} rule(s), path={}",
        plan.rules.len(),
        cfg.conf_path.display()
    );
    Ok(())
}

fn run_shell(cmd: &str) -> Result<(), ApplyError> {
    let output = Command::new("sh").arg("-c").arg(cmd).output()?;
    if output.status.success() {
        return Ok(());
    }
    let stdout = String::from_utf8_lossy(&output.stdout);
    let stderr = String::from_utf8_lossy(&output.stderr);
    let detail = format!(
        "status={} stdout={} stderr={}",
        output.status, stdout, stderr
    );
    Err(ApplyError::CommandFailed {
        cmd: cmd.to_string(),
        detail,
    })
}

fn quote_nginx_string(s: &str) -> String {
    format!("\"{}\"", s.replace('\\', "\\\\").replace('"', "\\\""))
}

fn escape_nginx_upstream_server(s: &str) -> String {
    if s.chars()
        .all(|c| c.is_ascii_alphanumeric() || matches!(c, '.' | '-' | '_' | ':' | '[' | ']'))
    {
        s.to_string()
    } else {
        quote_nginx_string(s)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use relay_shared::protocol::{LoadBalanceStrategy, NodeTransport};

    fn listener(
        rule_id: i64,
        port: u16,
        sni: &str,
        targets: &[&str],
        load_balance_strategy: LoadBalanceStrategy,
    ) -> ListenerConfig {
        ListenerConfig {
            rule_id,
            port,
            protocol: Protocol::Tcp,
            node_transport: NodeTransport::NginxSni,
            ws_path: None,
            sni: Some(sni.to_string()),
            targets: targets.iter().map(|t| t.to_string()).collect(),
            load_balance_strategy,
            upload_limit_bps: None,
            download_limit_bps: None,
            max_connections: None,
        }
    }

    #[test]
    fn renders_one_server_per_shared_port() {
        let plan = NginxSniPlan::from_listeners(
            &[
                listener(
                    1,
                    443,
                    "op1.example.com",
                    &["10.0.0.1:55443"],
                    LoadBalanceStrategy::First,
                ),
                listener(
                    2,
                    443,
                    "op2.example.com",
                    &["10.0.0.2:55443"],
                    LoadBalanceStrategy::First,
                ),
                listener(
                    3,
                    8443,
                    "op3.example.com",
                    &["10.0.0.3:55443"],
                    LoadBalanceStrategy::First,
                ),
            ],
            "127.0.0.1:9",
            "/var/log/nginx/sni-router.log",
        );
        let rendered = plan.render();
        assert!(rendered
            .contains("map \"$server_port:$ssl_preread_server_name\" $relay_panel_sni_backend"));
        assert!(rendered
            .contains("~*^443:op1\\.example\\.com$ relay_panel_sni_rule_1_443_op1_example_com;"));
        assert!(rendered
            .contains("~*^443:op2\\.example\\.com$ relay_panel_sni_rule_2_443_op2_example_com;"));
        assert!(rendered.contains("server 10.0.0.1:55443 max_fails=1 fail_timeout=10s;"));
        assert!(rendered.contains("listen 443;"));
        assert!(rendered.contains("listen 8443;"));
        assert!(rendered
            .contains("access_log \"/var/log/nginx/sni-router.log\" relay_panel_sni_traffic;"));
    }

    #[test]
    fn renders_upstreams_for_multi_target_strategies() {
        let plan = NginxSniPlan::from_listeners(
            &[
                listener(
                    1,
                    443,
                    "op1.example.com",
                    &["10.0.0.1:55443", "10.0.0.2:55443"],
                    LoadBalanceStrategy::RoundRobin,
                ),
                listener(
                    2,
                    443,
                    "op2.example.com",
                    &["10.0.0.3:55443", "10.0.0.4:55443"],
                    LoadBalanceStrategy::Failover,
                ),
                listener(
                    3,
                    443,
                    "op3.example.com",
                    &["10.0.0.5:55443", "10.0.0.6:55443"],
                    LoadBalanceStrategy::First,
                ),
            ],
            "127.0.0.1:8443",
            "/var/log/nginx/sni-router.log",
        );
        let rendered = plan.render();
        assert!(rendered.contains("upstream relay_panel_sni_rule_1_443_op1_example_com"));
        assert!(rendered.contains("server 10.0.0.1:55443 max_fails=1 fail_timeout=10s;"));
        assert!(rendered.contains("server 10.0.0.2:55443 max_fails=1 fail_timeout=10s;"));
        assert!(rendered.contains("server 10.0.0.4:55443 max_fails=1 fail_timeout=10s backup;"));
        assert!(rendered.contains("server 10.0.0.5:55443 max_fails=1 fail_timeout=10s;"));
        assert!(!rendered.contains("server 10.0.0.6:55443 max_fails=1 fail_timeout=10s;"));
    }

    #[test]
    fn looks_up_rule_id_by_port_and_sni() {
        let plan = NginxSniPlan::from_listeners(
            &[listener(
                7,
                443,
                "OP1.Example.COM",
                &["10.0.0.1:55443"],
                LoadBalanceStrategy::First,
            )],
            "127.0.0.1:8443",
            "/var/log/nginx/sni-router.log",
        );
        assert_eq!(plan.rule_id_for(443, "op1.example.com"), Some(7));
        assert_eq!(plan.rule_id_for(8443, "op1.example.com"), None);
    }
}
