#!/usr/bin/env bash
# DEPRECATED COMPATIBILITY INSTALLER: new Relay deployments must use the
# Panel Node Bootstrap SSH or Manual Bootstrap flow. Keep behavior unchanged
# for existing nodes; this script is no longer generated by the current UI.
#
# RelayPanel node installer - downloads and runs relay-node as a systemd service.
#
# Usage:
#   bash <(curl -fsSL https://github.com/pixingzoudaiyuexing/reality-panel/releases/download/v1.1.1/relay-node-install.sh) \
#     -t <NODE_TOKEN> -u <PANEL_URL> --version 1.1.1
#
# Options:
#   -t, --token         Node token (required, from the panel UI)
#   -u, --url           Panel URL, e.g. http://panel-ip:18888 (required)
#   -s, --service-name  systemd service name (default: relay-node)
#   -p, --proxy         Proxy for downloads, e.g. socks5://127.0.0.1:10808
#                       (or set RELAY_PROXY env var)
#   --version X.Y.Z     Install an exact unified Release version.
#   --nginx-sni         Enable Nginx Stream SNI mode.
#   --nginx-docker      Run the Nginx SNI router as a Docker container.
#   --openlist-port N   Use an existing local OpenList HTTP Docker site as the
#                       fallback, e.g. 5244 maps to http://127.0.0.1:5244.
#   --fallback-backend  Direct TLS fallback backend, e.g. 127.0.0.1:8443.
#   --fallback-certbot-domain DOMAIN
#                       Auto-issue and renew a Let's Encrypt certificate for
#                       the local HTTPS fallback wrapper.
#
# Environment:
#   RELAY_PROXY           Same as -p (e.g. socks5://127.0.0.1:10808)
#
# Idempotent re-runs: downloading to a temp file and swapping atomically means
# this script can be re-run to upgrade an already-running node. The running
# binary is only replaced AFTER the new one is fully downloaded and validated,
# so a failed download never breaks an existing install.
#
set -euo pipefail

# v1.0.9: move off the invocation directory immediately. If the script is run
# from a directory that has since been deleted (common when piping via
# `bash <(curl ...)` from a scratch dir), child processes inherit a dead cwd and
# fail with "shell-init: error retrieving current directory: getcwd". Anchoring
# to / (all work uses absolute paths anyway) avoids that class of error.
cd / 2>/dev/null || true

# Bump this when releasing a new version. The binary is downloaded from
# GitHub Releases assets.
SCRIPT_VERSION="1.1.1"
REPO="pixingzoudaiyuexing/reality-panel"

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

info()  { echo -e "${GREEN}[INFO]${NC}  $*"; }
warn()  { echo -e "${YELLOW}[WARN]${NC}  $*"; }
fail()  { echo -e "${RED}[FAIL]${NC}  $*"; exit 1; }

# ---------- Defaults ----------
NODE_TOKEN=""
PANEL_URL=""
SERVICE_NAME="relay-node"
PROXY="${RELAY_PROXY:-}"
NGINX_SNI="${NGINX_SNI:-0}"
SNI_NGINX_MODE="${NGINX_SNI_MODE:-host}"
SNI_NGINX_DOCKER_IMAGE="${NGINX_SNI_DOCKER_IMAGE:-nginx:1.27-alpine}"
SNI_NGINX_DOCKER_NAME="${NGINX_SNI_DOCKER_NAME:-}"
SNI_FALLBACK_PORT="${SNI_FALLBACK_PORT:-8443}"
SNI_FALLBACK_SERVER_NAME="${SNI_FALLBACK_SERVER_NAME:-localhost}"
SNI_FALLBACK_HTTP_UPSTREAM="${SNI_FALLBACK_HTTP_UPSTREAM:-}"
SNI_DEFAULT_BACKEND="${NGINX_SNI_DEFAULT_BACKEND:-}"
SNI_FALLBACK_CERT="${SNI_FALLBACK_CERT:-}"
SNI_FALLBACK_KEY="${SNI_FALLBACK_KEY:-}"
SNI_FALLBACK_CERTBOT_DOMAIN="${SNI_FALLBACK_CERTBOT_DOMAIN:-}"
SNI_FALLBACK_CERTBOT_EMAIL="${SNI_FALLBACK_CERTBOT_EMAIL:-}"
SNI_FALLBACK_CERTBOT_STAGING="${SNI_FALLBACK_CERTBOT_STAGING:-0}"
# v1.2: explicit node version override (--version X.Y.Z). When empty, the
# script resolves the latest stable unified Reality Panel release.
TARGET_VERSION=""

# ---------- Parse args ----------
while [[ $# -gt 0 ]]; do
    case "$1" in
        -t|--token)         NODE_TOKEN="$2"; shift 2 ;;
        -u|--url)           PANEL_URL="$2"; shift 2 ;;
        -s|--service-name)  SERVICE_NAME="$2"; shift 2 ;;
        -p|--proxy)         PROXY="$2"; shift 2 ;;
        --version)          TARGET_VERSION="$2"; shift 2 ;;
        --nginx-sni)        NGINX_SNI="1"; shift ;;
        --nginx-docker)     NGINX_SNI="1"; SNI_NGINX_MODE="docker"; shift ;;
        --nginx-mode)       SNI_NGINX_MODE="$2"; shift 2 ;;
        --nginx-docker-image) SNI_NGINX_DOCKER_IMAGE="$2"; shift 2 ;;
        --nginx-container-name) SNI_NGINX_DOCKER_NAME="$2"; shift 2 ;;
        --fallback-backend) SNI_DEFAULT_BACKEND="$2"; shift 2 ;;
        --fallback-http-upstream) SNI_FALLBACK_HTTP_UPSTREAM="$2"; shift 2 ;;
        --openlist-port)    SNI_FALLBACK_HTTP_UPSTREAM="127.0.0.1:$2"; shift 2 ;;
        --fallback-port)    SNI_FALLBACK_PORT="$2"; shift 2 ;;
        --fallback-name)    SNI_FALLBACK_SERVER_NAME="$2"; shift 2 ;;
        --fallback-cert)    SNI_FALLBACK_CERT="$2"; shift 2 ;;
        --fallback-key)     SNI_FALLBACK_KEY="$2"; shift 2 ;;
        --fallback-certbot-domain) SNI_FALLBACK_CERTBOT_DOMAIN="$2"; shift 2 ;;
        --fallback-certbot-email)  SNI_FALLBACK_CERTBOT_EMAIL="$2"; shift 2 ;;
        --fallback-certbot-staging) SNI_FALLBACK_CERTBOT_STAGING="1"; shift ;;
        -h|--help)
            echo "Usage: $0 -t <token> -u <panel-url> [-s <service-name>] [-p <proxy>] [--version X.Y.Z] [--nginx-sni --openlist-port 5244]"
            echo ""
            echo "Options:"
            echo "  -t, --token         Node token from the panel UI (required)"
            echo "  -u, --url           Panel URL, e.g. http://panel-ip:18888 (required)"
            echo "  -s, --service-name  systemd service name (default: relay-node)"
            echo "  -p, --proxy         Download proxy, e.g. socks5://127.0.0.1:10808"
            echo "  --version X.Y.Z     Install a specific unified release (default: latest stable)"
            echo "  --nginx-sni         Configure Nginx Stream SNI routing"
            echo "  --nginx-docker      Run the Nginx SNI router as a Docker container"
            echo "  --nginx-mode MODE   Nginx runtime for --nginx-sni: host or docker (default: host)"
            echo "  --nginx-docker-image IMAGE"
            echo "                       Docker image for --nginx-docker (default: nginx:1.27-alpine)"
            echo "  --nginx-container-name NAME"
            echo "                       Container name for --nginx-docker (default: <service-name>-nginx)"
            echo "  --openlist-port N   Use local OpenList HTTP Docker site as fallback, e.g. 5244"
            echo "  --fallback-http-upstream HOST:PORT"
            echo "                       HTTP upstream to wrap with local HTTPS, e.g. 127.0.0.1:5244"
            echo "  --fallback-backend HOST:PORT"
            echo "                       Direct TLS fallback backend; no HTTP wrapper is created"
            echo "  --fallback-port N   Local HTTPS wrapper port for --openlist-port/--fallback-http-upstream (default: 8443)"
            echo "  --fallback-name X   Fallback HTTPS server_name / self-signed CN (default: localhost)"
            echo "  --fallback-cert P   Existing PEM fullchain for fallback HTTPS wrapper"
            echo "  --fallback-key P    Existing PEM private key for fallback HTTPS wrapper"
            echo "  --fallback-certbot-domain DOMAIN"
            echo "                       Auto-issue and renew a Let's Encrypt cert for the fallback wrapper"
            echo "  --fallback-certbot-email EMAIL"
            echo "                       Email used for Let's Encrypt registration and notices"
            echo "  --fallback-certbot-staging"
            echo "                       Use Let's Encrypt staging for dry-run testing"
            echo ""
            echo "Environment:"
            echo "  RELAY_PROXY           Same as -p"
            echo "  NGINX_SNI=1           Same as --nginx-sni"
            echo "  NGINX_SNI_MODE=docker Same as --nginx-docker"
            echo "  NGINX_SNI_DOCKER_IMAGE / NGINX_SNI_DOCKER_NAME"
            echo "                         Same as --nginx-docker-image/--nginx-container-name"
            echo "  SNI_FALLBACK_HTTP_UPSTREAM Same as --fallback-http-upstream"
            echo "  NGINX_SNI_DEFAULT_BACKEND Same as --fallback-backend"
            echo "  SNI_FALLBACK_PORT     Same as --fallback-port"
            echo "  SNI_FALLBACK_SERVER_NAME Same as --fallback-name"
            echo "  SNI_FALLBACK_CERT / SNI_FALLBACK_KEY Same as --fallback-cert/--fallback-key"
            echo "  SNI_FALLBACK_CERTBOT_DOMAIN / SNI_FALLBACK_CERTBOT_EMAIL"
            echo "                       Same as --fallback-certbot-domain/--fallback-certbot-email"
            echo "  SNI_FALLBACK_CERTBOT_STAGING=1 Same as --fallback-certbot-staging"
            exit 0
            ;;
        *)
            fail "Unknown option: $1. Use -h for help."
            ;;
    esac
done

# ---------- Validate ----------
if [ -z "$NODE_TOKEN" ]; then
    fail "Missing required option: -t/--token. Get it from the panel's Device Groups page."
fi
if [ -z "$PANEL_URL" ]; then
    fail "Missing required option: -u/--url. Example: http://203.0.113.10:18888"
fi
case "$SNI_NGINX_MODE" in
    host|docker) ;;
    *) fail "--nginx-mode / NGINX_SNI_MODE must be either 'host' or 'docker'" ;;
esac
if [ -n "$SNI_NGINX_DOCKER_NAME" ] && ! [[ "$SNI_NGINX_DOCKER_NAME" =~ ^[A-Za-z0-9][A-Za-z0-9_.-]{0,127}$ ]]; then
    fail "--nginx-container-name / NGINX_SNI_DOCKER_NAME must contain only letters, numbers, dot, underscore, or dash"
fi
if [ -z "$SNI_NGINX_DOCKER_IMAGE" ]; then
    fail "--nginx-docker-image / NGINX_SNI_DOCKER_IMAGE cannot be empty"
fi
if ! [[ "$SNI_FALLBACK_PORT" =~ ^[0-9]+$ ]] || [ "$SNI_FALLBACK_PORT" -lt 1 ] || [ "$SNI_FALLBACK_PORT" -gt 65535 ]; then
    fail "--fallback-port must be an integer from 1 to 65535"
fi
if [ -n "$SNI_FALLBACK_HTTP_UPSTREAM" ] && [ -n "$SNI_DEFAULT_BACKEND" ]; then
    fail "Use either --fallback-http-upstream/--openlist-port OR --fallback-backend, not both"
fi
if { [ -n "$SNI_FALLBACK_CERT" ] && [ -z "$SNI_FALLBACK_KEY" ]; } || { [ -z "$SNI_FALLBACK_CERT" ] && [ -n "$SNI_FALLBACK_KEY" ]; }; then
    fail "--fallback-cert and --fallback-key must be provided together"
fi
if [ -n "$SNI_FALLBACK_HTTP_UPSTREAM" ]; then
    if [[ "$SNI_FALLBACK_HTTP_UPSTREAM" == *"://"* || "$SNI_FALLBACK_HTTP_UPSTREAM" == */* ]]; then
        fail "--fallback-http-upstream must be HOST:PORT, not a URL"
    fi
    upstream_port="${SNI_FALLBACK_HTTP_UPSTREAM##*:}"
    if [ "$upstream_port" = "$SNI_FALLBACK_HTTP_UPSTREAM" ] || ! [[ "$upstream_port" =~ ^[0-9]+$ ]] || [ "$upstream_port" -lt 1 ] || [ "$upstream_port" -gt 65535 ]; then
        fail "--openlist-port/--fallback-http-upstream must end with a port from 1 to 65535"
    fi
fi
case "$SNI_FALLBACK_CERTBOT_STAGING" in
    1|true|TRUE|yes|YES|on|ON) SNI_FALLBACK_CERTBOT_STAGING="1" ;;
    0|false|FALSE|no|NO|off|OFF|"") SNI_FALLBACK_CERTBOT_STAGING="0" ;;
    *) fail "--fallback-certbot-staging / SNI_FALLBACK_CERTBOT_STAGING must be boolean" ;;
esac
if [ -n "$SNI_FALLBACK_CERTBOT_DOMAIN" ]; then
    if [[ "$SNI_FALLBACK_CERTBOT_DOMAIN" == *"://"* || "$SNI_FALLBACK_CERTBOT_DOMAIN" == */* || "$SNI_FALLBACK_CERTBOT_DOMAIN" == \** ]]; then
        fail "--fallback-certbot-domain must be a plain hostname, not a URL or wildcard"
    fi
    if ! [[ "$SNI_FALLBACK_CERTBOT_DOMAIN" =~ ^[A-Za-z0-9]([A-Za-z0-9-]{0,61}[A-Za-z0-9])?(\.[A-Za-z0-9]([A-Za-z0-9-]{0,61}[A-Za-z0-9])?)+$ ]]; then
        fail "--fallback-certbot-domain must be a valid FQDN, e.g. op1.example.com"
    fi
    if [ -n "$SNI_DEFAULT_BACKEND" ]; then
        fail "--fallback-certbot-domain is for the local HTTPS wrapper; use it with --openlist-port/--fallback-http-upstream, not --fallback-backend"
    fi
    if [ -z "$SNI_FALLBACK_HTTP_UPSTREAM" ]; then
        fail "--fallback-certbot-domain requires --openlist-port or --fallback-http-upstream"
    fi
    if [ -n "$SNI_FALLBACK_CERT" ] || [ -n "$SNI_FALLBACK_KEY" ]; then
        fail "Use either --fallback-certbot-domain OR --fallback-cert/--fallback-key, not both"
    fi
    if [ "$SNI_FALLBACK_SERVER_NAME" = "localhost" ]; then
        SNI_FALLBACK_SERVER_NAME="$SNI_FALLBACK_CERTBOT_DOMAIN"
    fi
fi
if [ -n "$SNI_DEFAULT_BACKEND" ]; then
    if [[ "$SNI_DEFAULT_BACKEND" == *"://"* || "$SNI_DEFAULT_BACKEND" == */* ]]; then
        fail "--fallback-backend must be HOST:PORT, not a URL"
    fi
    backend_port="${SNI_DEFAULT_BACKEND##*:}"
    if [ "$backend_port" = "$SNI_DEFAULT_BACKEND" ] || ! [[ "$backend_port" =~ ^[0-9]+$ ]] || [ "$backend_port" -lt 1 ] || [ "$backend_port" -gt 65535 ]; then
        fail "--fallback-backend must end with a port from 1 to 65535"
    fi
fi

# ---------- Platform check ----------
if [ "$(uname -s)" != "Linux" ]; then
    fail "This installer only runs on Linux. Current OS: $(uname -s)"
fi
if [ "$(id -u)" -ne 0 ]; then
    fail "Please run as root (use sudo)."
fi

# ---------- Architecture detection ----------
ARCH_RAW="$(uname -m)"
case "$ARCH_RAW" in
    x86_64|amd64) ARCH="amd64" ;;
    *)
        fail "Unsupported architecture: $ARCH_RAW. Reality Panel v1 releases Linux amd64 only."
        ;;
esac
info "Detected architecture: $ARCH ($ARCH_RAW)"

install_pkg() {
    if command -v apt-get >/dev/null 2>&1; then
        DEBIAN_FRONTEND=noninteractive apt-get update -y -qq
        DEBIAN_FRONTEND=noninteractive apt-get install -y -qq "$@"
    elif command -v dnf >/dev/null 2>&1; then
        dnf install -y "$@"
    elif command -v yum >/dev/null 2>&1; then
        yum install -y "$@"
    else
        fail "No supported package manager found. Install required packages manually: $*"
    fi
}

install_nginx_support_packages() {
    if command -v apt-get >/dev/null 2>&1; then
        DEBIAN_FRONTEND=noninteractive apt-get update -y -qq
        DEBIAN_FRONTEND=noninteractive apt-get install -y -qq openssl ca-certificates
    else
        install_pkg openssl ca-certificates
    fi
}

ensure_docker_engine() {
    if ! command -v docker >/dev/null 2>&1; then
        info "Docker not found - installing via get.docker.com ..."
        command -v curl >/dev/null 2>&1 || install_pkg curl ca-certificates
        curl -fsSL https://get.docker.com | sh
    fi
    if command -v systemctl >/dev/null 2>&1; then
        systemctl enable --now docker || true
    fi
    if ! docker info >/dev/null 2>&1; then
        fail "Docker daemon is not running. Start Docker and re-run the installer."
    fi
}

ensure_line_in_file() {
    local file="$1"
    local line="$2"
    touch "$file"
    grep -Fqx "$line" "$file" || printf '%s\n' "$line" >> "$file"
}

shell_quote() {
    printf "'%s'" "$(printf '%s' "$1" | sed "s/'/'\\\\''/g")"
}

set_env_var() {
    local file="$1"
    local key="$2"
    local value="$3"
    sed -i "/^[#[:space:]]*${key}=.*/d" "$file"
    printf '%s=%s\n' "$key" "$(shell_quote "$value")" >> "$file"
}

write_nginx_docker_base_config() {
    mkdir -p "$NGINX_DOCKER_HTTP_DIR" "$NGINX_DOCKER_STREAM_DIR" "$NGINX_DOCKER_CERT_DIR" "$NGINX_DOCKER_LOG_DIR"
    touch "$NGINX_DOCKER_STREAM_CONF"
    cat > "$NGINX_DOCKER_CONF" <<NGINXEOF
user nginx;
worker_processes auto;
error_log ${NGINX_DOCKER_LOG_DIR}/error.log warn;
pid /tmp/nginx.pid;

events {
    worker_connections 1024;
}

stream {
    include /etc/nginx/stream.d/*.conf;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    access_log ${NGINX_DOCKER_LOG_DIR}/access.log;
    sendfile on;
    keepalive_timeout 65;

    include /etc/nginx/conf.d/*.conf;
}
NGINXEOF
}

start_nginx_docker_container() {
    ensure_docker_engine
    write_nginx_docker_base_config
    mkdir -p /etc/letsencrypt /var/www/relay-panel-certbot

    if ! docker image inspect "$SNI_NGINX_DOCKER_IMAGE" >/dev/null 2>&1; then
        info "Pulling Nginx Docker image: ${SNI_NGINX_DOCKER_IMAGE}"
        docker pull "$SNI_NGINX_DOCKER_IMAGE"
    fi

    docker rm -f "$SNI_NGINX_DOCKER_NAME" >/dev/null 2>&1 || true
    docker run -d \
        --name "$SNI_NGINX_DOCKER_NAME" \
        --restart unless-stopped \
        --network host \
        -v "${NGINX_DOCKER_CONF}:/etc/nginx/nginx.conf:ro" \
        -v "${NGINX_DOCKER_HTTP_DIR}:/etc/nginx/conf.d:ro" \
        -v "${NGINX_DOCKER_STREAM_DIR}:/etc/nginx/stream.d:ro" \
        -v "${NGINX_DOCKER_CERT_DIR}:/etc/nginx/relay-panel-certs:ro" \
        -v "/etc/letsencrypt:/etc/letsencrypt:ro" \
        -v "/var/www/relay-panel-certbot:/var/www/relay-panel-certbot:ro" \
        -v "${NGINX_DOCKER_LOG_DIR}:${NGINX_DOCKER_LOG_DIR}" \
        "$SNI_NGINX_DOCKER_IMAGE" >/dev/null
    info "Nginx Docker container is running: ${SNI_NGINX_DOCKER_NAME}"
}

nginx_runtime_test() {
    if [ "$SNI_NGINX_MODE" = "docker" ]; then
        docker exec "$SNI_NGINX_DOCKER_NAME" nginx -t
    else
        nginx -t
    fi
}

nginx_runtime_reload() {
    if [ "$SNI_NGINX_MODE" = "docker" ]; then
        docker exec "$SNI_NGINX_DOCKER_NAME" nginx -s reload || docker restart "$SNI_NGINX_DOCKER_NAME"
    else
        systemctl reload nginx || systemctl restart nginx
    fi
}

nginx_runtime_restart() {
    if [ "$SNI_NGINX_MODE" = "docker" ]; then
        start_nginx_docker_container
    else
        systemctl enable nginx
        systemctl restart nginx
    fi
}

install_certbot_if_needed() {
    command -v certbot >/dev/null 2>&1 && return 0

    info "Installing certbot for Let's Encrypt fallback certificate ..."
    if command -v apt-get >/dev/null 2>&1; then
        DEBIAN_FRONTEND=noninteractive apt-get update -y -qq
        DEBIAN_FRONTEND=noninteractive apt-get install -y -qq certbot
    else
        install_pkg certbot
    fi
}

configure_certbot_renew_hook() {
    local hook="/etc/letsencrypt/renewal-hooks/deploy/relay-panel-nginx-reload.sh"
    mkdir -p "$(dirname "$hook")"
    if [ "$SNI_NGINX_MODE" = "docker" ]; then
        cat > "$hook" <<HOOKEOF
#!/usr/bin/env bash
set -euo pipefail
if command -v docker >/dev/null 2>&1 && docker ps --format '{{.Names}}' | grep -Fxq '${SNI_NGINX_DOCKER_NAME}'; then
    docker exec '${SNI_NGINX_DOCKER_NAME}' nginx -s reload || docker restart '${SNI_NGINX_DOCKER_NAME}'
elif command -v systemctl >/dev/null 2>&1 && systemctl list-unit-files nginx.service >/dev/null 2>&1; then
    systemctl reload nginx || systemctl restart nginx
elif command -v nginx >/dev/null 2>&1; then
    nginx -s reload
fi
HOOKEOF
    else
        cat > "$hook" <<'HOOKEOF'
#!/usr/bin/env bash
set -euo pipefail
if command -v systemctl >/dev/null 2>&1 && systemctl list-unit-files nginx.service >/dev/null 2>&1; then
    systemctl reload nginx || systemctl restart nginx
elif command -v nginx >/dev/null 2>&1; then
    nginx -s reload
fi
HOOKEOF
    fi
    chmod 755 "$hook"
}

enable_certbot_auto_renewal() {
    local enabled=0

    if command -v systemctl >/dev/null 2>&1; then
        local timer
        for timer in certbot.timer certbot-renew.timer snap.certbot.renew.timer; do
            if systemctl list-unit-files "$timer" 2>/dev/null | grep -q "^${timer}"; then
                if systemctl enable --now "$timer"; then
                    info "Enabled certificate auto-renewal timer: ${timer}"
                    enabled=1
                    break
                else
                    warn "Failed to enable ${timer}; trying the next renewal option."
                fi
            fi
        done
    fi

    if [ "$enabled" != "1" ]; then
        mkdir -p /etc/cron.d
        cat > /etc/cron.d/relay-panel-certbot-renew <<'CRONEOF'
SHELL=/bin/sh
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
17 3,15 * * * root certbot renew --quiet
CRONEOF
        chmod 644 /etc/cron.d/relay-panel-certbot-renew
        warn "No certbot systemd timer was enabled; installed cron fallback: /etc/cron.d/relay-panel-certbot-renew"
    fi
}

issue_fallback_certbot_certificate() {
    [ -n "$SNI_FALLBACK_CERTBOT_DOMAIN" ] || return 0

    install_certbot_if_needed
    configure_certbot_renew_hook
    enable_certbot_auto_renewal

    local domain="$SNI_FALLBACK_CERTBOT_DOMAIN"
    local cert="/etc/letsencrypt/live/${domain}/fullchain.pem"
    local key="/etc/letsencrypt/live/${domain}/privkey.pem"
    if [ -s "$cert" ] && [ -s "$key" ]; then
        info "Using existing Let's Encrypt certificate for ${domain}"
    else
        info "Requesting Let's Encrypt certificate for ${domain} via nginx webroot ..."
        mkdir -p /var/www/relay-panel-certbot/.well-known/acme-challenge
        mkdir -p "$NGINX_HTTP_CONF_DIR"
        cat > "${NGINX_HTTP_CONF_DIR}/relay-panel-certbot-http.conf" <<NGINXEOF
server {
    listen 80;
    server_name ${domain};

    location ^~ /.well-known/acme-challenge/ {
        root /var/www/relay-panel-certbot;
        default_type "text/plain";
    }

    location / {
        return 404;
    }
}
NGINXEOF
        nginx_runtime_test
        nginx_runtime_reload

        local email_args=(--register-unsafely-without-email)
        if [ -n "$SNI_FALLBACK_CERTBOT_EMAIL" ]; then
            email_args=(-m "$SNI_FALLBACK_CERTBOT_EMAIL")
        fi
        local staging_args=()
        if [ "$SNI_FALLBACK_CERTBOT_STAGING" = "1" ]; then
            staging_args=(--staging)
        fi
        certbot certonly --webroot \
            -w /var/www/relay-panel-certbot \
            -d "$domain" \
            --non-interactive --agree-tos \
            --keep-until-expiring \
            "${email_args[@]}" \
            "${staging_args[@]}"
    fi

    SNI_FALLBACK_CERT="$cert"
    SNI_FALLBACK_KEY="$key"
}

ensure_nginx_stream_include() {
    if grep -Rqs "include /etc/nginx/stream.d/\\*.conf;" /etc/nginx/nginx.conf /etc/nginx/conf.d 2>/dev/null; then
        return
    fi
    cat > /etc/nginx/relay-panel-stream.conf <<'NGINXEOF'
stream {
    include /etc/nginx/stream.d/*.conf;
}
NGINXEOF
    ensure_line_in_file /etc/nginx/nginx.conf "include /etc/nginx/relay-panel-stream.conf;"
}

configure_nginx_sni() {
    [ "$NGINX_SNI" = "1" ] || return 0

    info "Configuring Nginx Stream SNI mode (${SNI_NGINX_MODE}) ..."
    install_nginx_support_packages

    if [ "$SNI_NGINX_MODE" = "docker" ]; then
        NGINX_HTTP_CONF_DIR="$NGINX_DOCKER_HTTP_DIR"
        NGINX_STREAM_CONF_DIR="$NGINX_DOCKER_STREAM_DIR"
        NGINX_CERT_DIR="$NGINX_DOCKER_CERT_DIR"
        NGINX_ACCESS_LOG_PATH="$NGINX_DOCKER_LOG_DIR/sni-router.log"
        NGINX_SNI_CONF_PATH="$NGINX_DOCKER_STREAM_CONF"
        rm -f "${NGINX_DOCKER_HTTP_DIR}/relay-panel-fallback.conf"
        start_nginx_docker_container
    else
        if command -v apt-get >/dev/null 2>&1; then
            DEBIAN_FRONTEND=noninteractive apt-get update -y -qq
            DEBIAN_FRONTEND=noninteractive apt-get install -y -qq nginx openssl ca-certificates
            if apt-cache show libnginx-mod-stream >/dev/null 2>&1; then
                DEBIAN_FRONTEND=noninteractive apt-get install -y -qq libnginx-mod-stream
            fi
        else
            install_pkg nginx openssl ca-certificates
        fi
        NGINX_HTTP_CONF_DIR="/etc/nginx/conf.d"
        NGINX_STREAM_CONF_DIR="/etc/nginx/stream.d"
        NGINX_CERT_DIR="/etc/nginx/relay-panel-certs"
        NGINX_ACCESS_LOG_PATH="/var/log/nginx/sni-router.log"
        NGINX_SNI_CONF_PATH="/etc/nginx/stream.d/relay-panel-sni.conf"
        mkdir -p "$NGINX_STREAM_CONF_DIR" "$NGINX_CERT_DIR" /var/log/nginx
        ensure_nginx_stream_include
    fi

    if [ -n "$SNI_FALLBACK_HTTP_UPSTREAM" ]; then
        info "Configuring local HTTPS fallback wrapper -> http://${SNI_FALLBACK_HTTP_UPSTREAM}"
        issue_fallback_certbot_certificate
        local cert_host="${SNI_FALLBACK_CERT:-${NGINX_CERT_DIR}/fallback.crt}"
        local key_host="${SNI_FALLBACK_KEY:-${NGINX_CERT_DIR}/fallback.key}"
        local cert_nginx="$cert_host"
        local key_nginx="$key_host"
        if [ "$SNI_NGINX_MODE" = "docker" ]; then
            if [ -n "$SNI_FALLBACK_CERT" ] || [ -n "$SNI_FALLBACK_KEY" ]; then
                if [[ "$cert_host" == /etc/letsencrypt/* && "$key_host" == /etc/letsencrypt/* ]]; then
                    cert_nginx="$cert_host"
                    key_nginx="$key_host"
                elif [[ "$cert_host" == "$NGINX_DOCKER_CERT_DIR/"* && "$key_host" == "$NGINX_DOCKER_CERT_DIR/"* ]]; then
                    cert_nginx="/etc/nginx/relay-panel-certs/${cert_host#"$NGINX_DOCKER_CERT_DIR/"}"
                    key_nginx="/etc/nginx/relay-panel-certs/${key_host#"$NGINX_DOCKER_CERT_DIR/"}"
                else
                    [ -s "$cert_host" ] || fail "Fallback certificate not found or empty: $cert_host"
                    [ -s "$key_host" ] || fail "Fallback key not found or empty: $key_host"
                    cp "$cert_host" "$NGINX_DOCKER_CERT_DIR/custom-fullchain.pem"
                    cp "$key_host" "$NGINX_DOCKER_CERT_DIR/custom-privkey.pem"
                    chmod 600 "$NGINX_DOCKER_CERT_DIR/custom-privkey.pem"
                    cert_host="$NGINX_DOCKER_CERT_DIR/custom-fullchain.pem"
                    key_host="$NGINX_DOCKER_CERT_DIR/custom-privkey.pem"
                    cert_nginx="/etc/nginx/relay-panel-certs/custom-fullchain.pem"
                    key_nginx="/etc/nginx/relay-panel-certs/custom-privkey.pem"
                    warn "Copied explicit fallback cert/key into ${NGINX_DOCKER_CERT_DIR}; re-run the installer after renewing those external files."
                fi
            else
                cert_nginx="/etc/nginx/relay-panel-certs/fallback.crt"
                key_nginx="/etc/nginx/relay-panel-certs/fallback.key"
            fi
        fi
        if [ -n "$SNI_FALLBACK_CERT" ] || [ -n "$SNI_FALLBACK_KEY" ]; then
            [ -s "$cert_host" ] || fail "Fallback certificate not found or empty: $cert_host"
            [ -s "$key_host" ] || fail "Fallback key not found or empty: $key_host"
        elif [ ! -s "$cert_host" ] || [ ! -s "$key_host" ]; then
            openssl req -x509 -newkey rsa:2048 -nodes -days 3650 \
                -subj "/CN=${SNI_FALLBACK_SERVER_NAME}" \
                -keyout "$key_host" -out "$cert_host" >/dev/null 2>&1
            chmod 600 "$key_host"
        fi

        mkdir -p "$NGINX_HTTP_CONF_DIR"
        cat > "${NGINX_HTTP_CONF_DIR}/relay-panel-fallback.conf" <<NGINXEOF
server {
    listen 127.0.0.1:${SNI_FALLBACK_PORT} ssl;
    server_name ${SNI_FALLBACK_SERVER_NAME};

    ssl_certificate ${cert_nginx};
    ssl_certificate_key ${key_nginx};

    location / {
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_pass http://${SNI_FALLBACK_HTTP_UPSTREAM};
    }
}
NGINXEOF
        SNI_DEFAULT_BACKEND="127.0.0.1:${SNI_FALLBACK_PORT}"
    elif [ -z "$SNI_DEFAULT_BACKEND" ]; then
        warn "No fallback backend configured. Unmatched SNI will use 127.0.0.1:9 and fail closed."
        warn "For OpenList Docker, re-run with: --nginx-sni --openlist-port 5244"
        SNI_DEFAULT_BACKEND="127.0.0.1:9"
    fi

    nginx_runtime_test
    nginx_runtime_restart
}

# ---------- Install dirs ----------
INSTALL_DIR="/opt/${SERVICE_NAME}"
BINARY="${INSTALL_DIR}/relay-node"
if [ -z "$SNI_NGINX_DOCKER_NAME" ]; then
    SNI_NGINX_DOCKER_NAME="${SERVICE_NAME}-nginx"
fi
NGINX_DOCKER_ROOT="${INSTALL_DIR}/nginx"
NGINX_DOCKER_CONF="${NGINX_DOCKER_ROOT}/nginx.conf"
NGINX_DOCKER_HTTP_DIR="${NGINX_DOCKER_ROOT}/conf.d"
NGINX_DOCKER_STREAM_DIR="${NGINX_DOCKER_ROOT}/stream.d"
NGINX_DOCKER_STREAM_CONF="${NGINX_DOCKER_STREAM_DIR}/relay-panel-sni.conf"
NGINX_DOCKER_CERT_DIR="${NGINX_DOCKER_ROOT}/certs"
NGINX_DOCKER_LOG_DIR="${NGINX_DOCKER_ROOT}/logs"
NGINX_HTTP_CONF_DIR="/etc/nginx/conf.d"
NGINX_STREAM_CONF_DIR="/etc/nginx/stream.d"
NGINX_CERT_DIR="/etc/nginx/relay-panel-certs"
NGINX_ACCESS_LOG_PATH="/var/log/nginx/sni-router.log"
NGINX_SNI_CONF_PATH="/etc/nginx/stream.d/relay-panel-sni.conf"
# Temp download target. We never curl directly onto $BINARY because if the
# service is running, the kernel refuses writes to the executing file with
# ETXTBSY ("Text file busy"). Downloading to .tmp sidesteps that entirely;
# the atomic mv happens only after the service is stopped.
TMP_BINARY="${BINARY}.tmp"

# ---------- Resolve the install version ----------
# Reality Panel ships Panel and Node from the same v* GitHub Release. Default
# installation resolves GitHub's latest stable release; --version permits an
# explicit stable or prerelease tag. There is no branch, mirror, or local fallback.
resolve_node_version() {
    # $1 = proxy arg ("" or "--proxy X"). Returns the bare version on stdout.
    local proxy_args="$1"
    local latest_url
    latest_url=$(curl -fsSL --connect-timeout 10 --max-time 20 $proxy_args \
        -o /dev/null -w '%{url_effective}' "https://github.com/${REPO}/releases/latest") || return 1
    printf '%s\n' "${latest_url##*/v}"
}

if [ -z "$TARGET_VERSION" ]; then
    info "Querying GitHub for the latest stable Reality Panel release…"
    PROXY_ARG=""
    [ -n "$PROXY" ] && PROXY_ARG="--proxy $PROXY"
    LATEST_NODE=$(resolve_node_version "$PROXY_ARG")
    if [ -n "$LATEST_NODE" ]; then
        TARGET_VERSION="$LATEST_NODE"
        info "Latest node release: $TARGET_VERSION"
    else
        fail "Could not resolve the latest stable GitHub Release. Use --version $SCRIPT_VERSION to pin an existing release."
    fi
else
    info "Installing node version: $TARGET_VERSION (pinned via --version)"
fi

# ---------- Already-latest check ----------
# v1.2: if the installed binary already reports this version, do NOT re-download
# or replace the binary (avoids a needless stop/swap/restart of a working node).
# BUT the operator may be re-running the installer to point the node at a NEW
# panel URL / token or to refresh the systemd unit — so we still rewrite
# start.sh, the env file, and the service file, then restart, below. The binary
# download/swap is the only step skipped (gated by ALREADY_AT_VERSION).
ALREADY_AT_VERSION=0
if [ -x "$BINARY" ]; then
    INSTALLED_VERSION="$("$BINARY" --version 2>/dev/null | grep -oE '[0-9]+\.[0-9]+\.[0-9]+(-[0-9A-Za-z.-]+)?' | head -n1 || true)"
    if [ -n "$INSTALLED_VERSION" ] && [ "$INSTALLED_VERSION" = "$TARGET_VERSION" ]; then
        info "Already at node version $TARGET_VERSION — skipping binary download; refreshing panel/token/service config."
        ALREADY_AT_VERSION=1
    else
        [ -n "$INSTALLED_VERSION" ] && info "Installed version: $INSTALLED_VERSION → upgrading to $TARGET_VERSION"
    fi
fi

# v1.2: skip the binary download/verify/swap entirely when already at the
# target version (ALREADY_AT_VERSION=1). The config/service rewrite below still
# runs so a re-invocation with a new -t/-u refreshes the node's panel binding.
if [ "$ALREADY_AT_VERSION" != "1" ]; then

# ---------- Build download URL ----------
# Node binaries are available only from the matching unified GitHub Release.
ASSET_NAME="reality-node-linux-${ARCH}"
DOWNLOAD_URL="https://github.com/${REPO}/releases/download/v${TARGET_VERSION}/${ASSET_NAME}"
info "Download URL: $DOWNLOAD_URL"

# ---------- Download binary to temp file ----------
# curl flags: follow redirects, fail on HTTP error, show progress bar,
# connect timeout 10s, total timeout 120s, retry 3x with 2s delay.
CURL_OPTS=(-fL --progress-bar --connect-timeout 10 --max-time 120 --retry 3 --retry-delay 2 --retry-connrefused)
if [ -n "$PROXY" ]; then
    info "Using proxy: $PROXY"
    CURL_OPTS+=(--proxy "$PROXY")
fi

info "Downloading relay-node v${TARGET_VERSION} (${ARCH}) ..."
info "  URL: $DOWNLOAD_URL"
mkdir -p "$INSTALL_DIR"

# Always start from a clean temp file so a previous failed run cannot leave
# a half-written file that passes the ELF check by accident.
rm -f "$TMP_BINARY"

if ! curl "${CURL_OPTS[@]}" "$DOWNLOAD_URL" -o "$TMP_BINARY"; then
    rm -f "$TMP_BINARY"
    echo ""
    fail "Download failed. Possible causes:
  - GitHub Releases is blocked or slow in your network
  - Release v${TARGET_VERSION} does not have asset ${ASSET_NAME}
  - Proxy is misconfigured (if you passed -p)

Try one of:
  1. Use a proxy:     $0 -t <token> -u <url> -p socks5://127.0.0.1:10808
  2. Download manually:
     curl -fL -o relay-node '${DOWNLOAD_URL}'
     Then copy to ${BINARY}

Note: the existing binary (if any) was NOT touched by this failed download."
fi

# ---------- Verify SHA256 checksum (supply-chain integrity) ----------
# Every unified GitHub Release publishes one SHA256SUMS manifest. We extract
# the exact asset entry so a tampered/truncated/replaced binary
# (MITM, compromised mirror, CDN cache poisoning) is caught BEFORE it replaces
# the working binary. The existing binary is NOT touched on verification
# failure (same guarantee as a failed download).
#
# The matching GitHub Release checksum is required. Missing or mismatched
# checksum data is a hard failure before the running binary is touched.
CHECKSUM_URL="https://github.com/${REPO}/releases/download/v${TARGET_VERSION}/SHA256SUMS"
TMP_CHECKSUM="${TMP_BINARY}.SHA256SUMS"
    # Reuse the binary download's redirect, retry, timeout, and proxy options.
    if curl "${CURL_OPTS[@]}" "$CHECKSUM_URL" -o "$TMP_CHECKSUM"; then
        EXPECTED=$(awk -v name="$ASSET_NAME" \
            '$2 == name || $2 == ("*" name) { print $1 }' "$TMP_CHECKSUM")
        EXPECTED_COUNT=$(printf '%s\n' "$EXPECTED" | sed '/^$/d' | wc -l | tr -d ' ')
        # Compute the actual hash, trying the common tool variants in order.
        #   sha256sum <file> | awk '{print $1}'   (GNU coreutils, BusyBox)
        #   shasum -a 256 <file> | awk '{print $1}' (macOS, some BSD-based)
        #   sha256 <file>   (Alpine/FreeBSD: prints just the hash)
        ACTUAL=""
        if command -v sha256sum >/dev/null 2>&1; then
            ACTUAL=$(sha256sum "$TMP_BINARY" 2>/dev/null | awk '{ print $1 }')
        elif command -v shasum >/dev/null 2>&1; then
            ACTUAL=$(shasum -a 256 "$TMP_BINARY" 2>/dev/null | awk '{ print $1 }')
        elif command -v sha256 >/dev/null 2>&1; then
            ACTUAL=$(sha256 "$TMP_BINARY" 2>/dev/null | awk '{ print $1 }')
        fi
        # Normalize both to lowercase hex so a case difference never causes a
        # false mismatch (some tools uppercase).
        EXPECTED_LC=$(printf '%s' "$EXPECTED" | tr '[:upper:]' '[:lower:]')
        ACTUAL_LC=$(printf '%s' "$ACTUAL" | tr '[:upper:]' '[:lower:]')
        if [ "$EXPECTED_COUNT" != "1" ] || ! [[ "$EXPECTED" =~ ^[0-9A-Fa-f]{64}$ ]]; then
            rm -f "$TMP_BINARY" "$TMP_CHECKSUM"
            fail "SHA256SUMS has no unique valid entry for ${ASSET_NAME}.
The download was discarded."
        elif [ -z "$ACTUAL_LC" ]; then
            rm -f "$TMP_BINARY" "$TMP_CHECKSUM"
            fail "No sha256 tool found (tried sha256sum, shasum, sha256).
Cannot verify the downloaded binary. Install one of these. The existing binary was NOT touched."
        elif [ "$ACTUAL_LC" = "$EXPECTED_LC" ]; then
            info "Checksum verified (sha256 OK)."
        else
            rm -f "$TMP_BINARY" "$TMP_CHECKSUM"
            fail "Checksum verification FAILED for ${ASSET_NAME}.
Expected: $EXPECTED
Actual:   $ACTUAL

The downloaded binary does not match the published sha256. This indicates a
truncated, corrupted, or tampered download. The existing binary was NOT touched."
        fi
        rm -f "$TMP_CHECKSUM"
    else
        # GitHub Releases is REQUIRED to ship the manifest. Missing = hard fail.
        rm -f "$TMP_BINARY" "$TMP_CHECKSUM"
        fail "Checksum manifest not found at ${CHECKSUM_URL}.
Release v${TARGET_VERSION} is expected to publish SHA256SUMS. The download was discarded."
    fi

# ---------- Validate downloaded temp file ----------
# Check it is not an HTML error page. Use two methods:
#   1. Read the first 4 bytes - ELF binaries start with 0x7f 'E' 'L' 'F'
#   2. If `file` command exists, use it as a secondary check
# This avoids depending on `file` being installed (many minimal images lack it).
ELF_MAGIC=$(head -c 4 "$TMP_BINARY" 2>/dev/null | xxd -p 2>/dev/null || od -A n -t x1 -N 4 "$TMP_BINARY" 2>/dev/null | tr -d ' \n')

if [ "$ELF_MAGIC" != "7f454c46" ]; then
    # Not an ELF - try `file` for a better error message
    FILE_DESC=$(file -b "$TMP_BINARY" 2>/dev/null || echo "not an ELF binary")
    rm -f "$TMP_BINARY"
    fail "Downloaded file is not a valid binary (${FILE_DESC}).
The download URL may have returned an error page. Check:
  ${DOWNLOAD_URL}

Note: the existing binary (if any) was NOT touched."
fi

FILE_SIZE=$(stat -c%s "$TMP_BINARY" 2>/dev/null || stat -f%z "$TMP_BINARY" 2>/dev/null || echo 0)
if [ "$FILE_SIZE" -lt 100000 ]; then
    rm -f "$TMP_BINARY"
    fail "Downloaded file is too small (${FILE_SIZE} bytes). Expected a multi-MB binary.

Note: the existing binary (if any) was NOT touched."
fi

# ---------- Atomic install: stop service, swap binary ----------
# We stop the service ONLY after the new binary is fully downloaded and
# validated. This guarantees a failed download or validation never leaves
# the node without a working binary.
#
# Why stop at all: writing over a running ELF fails with ETXTBSY
# ("Text file busy"). The download went to .tmp so we avoided that during
# curl, but we still stop before the swap so the old binary releases cleanly
# and the new one starts from a known state.
if systemctl list-unit-files 2>/dev/null | grep -q "^${SERVICE_NAME}\.service"; then
    if systemctl is-active --quiet "$SERVICE_NAME"; then
        info "Stopping existing ${SERVICE_NAME} service for binary swap ..."
        systemctl stop "$SERVICE_NAME" || warn "systemctl stop returned non-zero (continuing)"
    else
        info "Existing ${SERVICE_NAME} service detected but not running."
    fi
else
    info "No existing ${SERVICE_NAME} service detected (fresh install)."
fi

# mv -f on the same filesystem is a single rename(2) syscall: atomic and
# never partial. The old running binary (if any) keeps its inode alive for
# the already-open file descriptors, so this cannot corrupt anything.
mv -f "$TMP_BINARY" "$BINARY"
chmod +x "$BINARY"
info "Binary installed: ${BINARY} ($(( FILE_SIZE / 1024 / 1024 )) MB, ELF ${ARCH})"

fi  # end ALREADY_AT_VERSION skip (binary download/swap)

# ---------- Write start.sh ----------
# IMPORTANT: the here-doc uses quoted 'EOF' delimiter so NOTHING is expanded
# at install time - all values are written literally. This prevents bugs like
# $0 being /dev/fd/63 when the installer runs via bash <(curl ...).
START_SH="${INSTALL_DIR}/start.sh"
info "Writing start script: $START_SH"
cat > "$START_SH" <<'STARTEOF'
#!/usr/bin/env bash
set -euo pipefail
cd "/opt/relay-node"
export PANEL_URL="__PANEL_URL__"
export NODE_TOKEN="__NODE_TOKEN__"
export POLL_INTERVAL="${POLL_INTERVAL:-10}"
export RUST_LOG="${RUST_LOG:-info}"
# Optional config sourced from relay-node.env if present (written by the
# installer with commented examples; edit it to set LISTEN_IPV4/LISTEN_IPV6,
# OUTBOUND_INTERFACE/OUTBOUND_BIND_IPV4, or TLS_CERT_PATH/TLS_KEY_PATH). If the
# file doesn't exist, all of these stay unset and the node uses its defaults
# (dual-stack listen, system-routed egress, no TLS).
# NOTE: path is hardcoded (/opt/relay-node) because this script runs with set -u
# and INSTALL_DIR is not defined in the generated start.sh context.
if [ -f "/opt/relay-node/relay-node.env" ]; then
    set -a
    . "/opt/relay-node/relay-node.env"
    set +a
fi
exec ./relay-node
STARTEOF

# Replace the placeholders with actual values (safe - no shell expansion).
sed -i "s|__PANEL_URL__|${PANEL_URL}|" "$START_SH"
sed -i "s|__NODE_TOKEN__|${NODE_TOKEN}|" "$START_SH"
chmod 700 "$START_SH"

# Safety check: make sure /dev/fd did not leak into the file.
if grep -q '/dev/fd' "$START_SH" 2>/dev/null; then
    fail "start.sh generated incorrectly (contains /dev/fd). Aborting."
fi

# v0.4.1: create the certs directory + example env file for TLS Simple.
# The operator places their cert+key here (or points the env file elsewhere).
CERTS_DIR="${INSTALL_DIR}/certs"
mkdir -p "$CERTS_DIR"
chmod 700 "$CERTS_DIR"

# Write an example env file if one doesn't exist (don't overwrite an existing
# one — the operator may have configured it).
ENV_FILE="${INSTALL_DIR}/relay-node.env"
if [ ! -f "$ENV_FILE" ]; then
    info "Writing example env file: $ENV_FILE (edit to tune listen / egress / TLS)"
    cat > "$ENV_FILE" <<'ENVEOF'
# relay-node optional environment. start.sh sources this file (set -a), so any
# variable set here is exported to relay-node. All values below are commented:
# the defaults already enable IPv4+IPv6 listening with system-routed egress.

# ── v1.0.5: dual-stack inbound listen (TCP/UDP) ──
# By default every rule listens on BOTH 0.0.0.0 and :: (separate sockets, the
# IPv6 one is IPV6_V6ONLY). Set a family's variable EMPTY to disable it.
#   LISTEN_IPV4=0.0.0.0      # empty → IPv4 disabled (IPv6-only node)
#   LISTEN_IPV6=::           # empty → IPv6 disabled (IPv4-only node)

# ── v1.0.5: IPv4 outbound egress for multi-NIC servers ──
# When inbound (e.g. public IPv6 on ens19) and outbound (e.g. IPv4 via ens18)
# use different interfaces, force the source so connections leave the right NIC.
# Priority: OUTBOUND_BIND_IPV4 > OUTBOUND_INTERFACE > auto (system routing).
# The example values below are ILLUSTRATIVE — use your own server's NIC/address.
#   OUTBOUND_INTERFACE=ens18         # node resolves this NIC's IPv4 to bind
#   OUTBOUND_BIND_IPV4=10.0.2.61     # or pin the exact source IPv4 (overrides above)

# ── v1.2.1: public-IP detection endpoints ──
# The node does NOT read its own NIC: it asks an external service what source
# address the outside sees, which is what makes a NAT'd host (private NIC IP,
# mapped elastic IP) report the right address. The answer becomes the IP and
# country flag shown on the panel; failure shows "-" and never affects
# forwarding. Re-checked every 30 minutes, so restart to apply a change.
#
# Override only if the defaults are unreachable from this server. Whatever you
# point these at MUST return a BARE IP and MUST be family-pinned — the node
# discards an answer from the wrong family, so a dual-stack endpoint (one that
# replies with whichever family you connected over) leaves the address blank on
# dual-stack hosts. Test with: curl -s --max-time 5 <url>
#   PUBLIC_IPV4_CHECK_URL=https://ipv4.icanhazip.com
#   PUBLIC_IPV6_CHECK_URL=https://ipv6.icanhazip.com

# ── TLS Simple certificate configuration (v0.4.1) ──
# Uncomment and set these to enable TLS Simple ingress on this node.
# The cert must be PEM format (fullchain recommended); the key must be PEM
# (PKCS#8, PKCS#1 RSA, or SEC1 EC). The key file MUST be chmod 600.
#   TLS_CERT_PATH=/opt/relay-node/certs/fullchain.pem
#   TLS_KEY_PATH=/opt/relay-node/certs/privkey.pem

# ── Reality/SNI forwarding via Nginx Stream ──
# The installer can populate these automatically with --nginx-sni.
# For an OpenList Docker site on 127.0.0.1:5244, run with:
#   --nginx-sni --openlist-port 5244
# Or keep the SNI router itself in Docker:
#   --nginx-sni --nginx-docker --openlist-port 5244
#   NGINX_SNI_ENABLED=1
#   NGINX_SNI_CONF_PATH=/etc/nginx/stream.d/relay-panel-sni.conf
#   NGINX_SNI_DEFAULT_BACKEND=127.0.0.1:8443
#   NGINX_SNI_ACCESS_LOG_PATH=/var/log/nginx/sni-router.log
#   NGINX_SNI_TRAFFIC_STATE_PATH=/opt/relay-node/nginx-sni-log.offset
ENVEOF
    chmod 600 "$ENV_FILE"
fi

configure_nginx_sni
if [ "$NGINX_SNI" = "1" ]; then
    info "Writing nginx_sni environment to $ENV_FILE"
    set_env_var "$ENV_FILE" "NGINX_SNI_ENABLED" "1"
    set_env_var "$ENV_FILE" "NGINX_SNI_CONF_PATH" "$NGINX_SNI_CONF_PATH"
    set_env_var "$ENV_FILE" "NGINX_SNI_DEFAULT_BACKEND" "$SNI_DEFAULT_BACKEND"
    if [ "$SNI_NGINX_MODE" = "docker" ]; then
        set_env_var "$ENV_FILE" "NGINX_SNI_TEST_CMD" "docker exec ${SNI_NGINX_DOCKER_NAME} nginx -t"
        set_env_var "$ENV_FILE" "NGINX_SNI_RELOAD_CMD" "docker exec ${SNI_NGINX_DOCKER_NAME} nginx -s reload"
    else
        set_env_var "$ENV_FILE" "NGINX_SNI_TEST_CMD" "nginx -t"
        set_env_var "$ENV_FILE" "NGINX_SNI_RELOAD_CMD" "systemctl reload nginx"
    fi
    set_env_var "$ENV_FILE" "NGINX_SNI_ACCESS_LOG_PATH" "$NGINX_ACCESS_LOG_PATH"
    set_env_var "$ENV_FILE" "NGINX_SNI_TRAFFIC_STATE_PATH" "${INSTALL_DIR}/nginx-sni-log.offset"
    chmod 600 "$ENV_FILE"
    if [ "$SNI_NGINX_MODE" = "docker" ]; then
        cat > "${INSTALL_DIR}/uninstall-nginx-docker.sh" <<UNINSTALLEOF
#!/usr/bin/env bash
set -euo pipefail
docker rm -f '${SNI_NGINX_DOCKER_NAME}' >/dev/null 2>&1 || true
rm -rf '${NGINX_DOCKER_ROOT}'
echo "Removed Nginx Docker container and files for Reality Panel."
UNINSTALLEOF
        chmod 700 "${INSTALL_DIR}/uninstall-nginx-docker.sh"
    fi
fi

# ---------- Write systemd service ----------
SERVICE_FILE="/etc/systemd/system/${SERVICE_NAME}.service"
SERVICE_AFTER="network-online.target"
SERVICE_WANTS="network-online.target"
if [ "$NGINX_SNI" = "1" ] && [ "$SNI_NGINX_MODE" = "docker" ]; then
    SERVICE_AFTER="network-online.target docker.service"
    SERVICE_WANTS="network-online.target docker.service"
fi
info "Writing systemd service: $SERVICE_FILE"
cat > "$SERVICE_FILE" <<SVCEOF
[Unit]
Description=RelayNode forwarding service
After=${SERVICE_AFTER}
Wants=${SERVICE_WANTS}

[Service]
Type=simple
RuntimeDirectory=relay-node
RuntimeDirectoryMode=0755
WorkingDirectory=${INSTALL_DIR}
ExecStart=/bin/bash ${START_SH}
Restart=always
RestartSec=3
LimitNOFILE=65536

[Install]
WantedBy=multi-user.target
SVCEOF

# ---------- Enable and start ----------
info "Enabling and starting ${SERVICE_NAME} ..."
systemctl daemon-reload
systemctl enable "$SERVICE_NAME"
# restart handles both fresh start and post-upgrade start.
systemctl restart "$SERVICE_NAME"

# ---------- Verify ----------
sleep 2
if systemctl is-active --quiet "$SERVICE_NAME"; then
    info "Service ${SERVICE_NAME} is running."
else
    warn "Service ${SERVICE_NAME} failed to start. Recent logs:"
    echo "---"
    journalctl -u "$SERVICE_NAME" --no-pager -n 50 2>/dev/null || echo "(journalctl not available)"
    echo "---"
fi

# ---------- Done ----------
echo ""
info "=========================================="
info " relay-node installed successfully!"
info "=========================================="
echo ""
echo "  Service:   ${SERVICE_NAME}"
echo "  Binary:    ${BINARY}"
echo "  Version:   v${TARGET_VERSION}"
echo "  Panel:     ${PANEL_URL}"
echo ""
echo "  Logs:      journalctl -u ${SERVICE_NAME} -f"
echo "  Status:    systemctl status ${SERVICE_NAME}"
echo "  Stop:      systemctl stop ${SERVICE_NAME}"
echo "  Restart:   systemctl restart ${SERVICE_NAME}"
echo "  Upgrade:   re-run this installer with the same -t/-u flags"
echo "  Uninstall: systemctl disable --now ${SERVICE_NAME}; rm -f ${SERVICE_FILE}; rm -rf ${INSTALL_DIR}"
if [ "$NGINX_SNI" = "1" ] && [ "$SNI_NGINX_MODE" = "docker" ]; then
    echo "  Nginx:     docker ps --filter name=${SNI_NGINX_DOCKER_NAME}"
    echo "  Remove Nginx Docker: docker rm -f ${SNI_NGINX_DOCKER_NAME}; rm -rf ${NGINX_DOCKER_ROOT}"
fi
echo ""
